# Databricks notebook source
# MAGIC %md
# MAGIC ## df = spark.read.format("delta").table("schema.tabela")
# MAGIC
# MAGIC Gerando um dataframe dos delta lake no container bronze do Azure Data Lake Storage

# COMMAND ----------


df_ar_condicionados   = spark.read.format("delta").table("silver.ar_condicionados")
df_clientes          = spark.read.format("delta").table("silver.clientes")
df_vendedores        = spark.read.format("delta").table("silver.vendedores")
df_vendas            = spark.read.format("delta").table("silver.vendas")

# COMMAND ----------

# MAGIC %md
# MAGIC ### Adicionando metadados de data e hora de processamento e nome do arquivo de origem

# COMMAND ----------

df_ar_condicionados.createOrReplaceTempView("ar_condicionados")
df_clientes.createOrReplaceTempView("clientes")
df_vendedores.createOrReplaceTempView("vendedores")

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from silver.ar_condicionados

# COMMAND ----------

# MAGIC %sql
# MAGIC drop table if exists gold.dim_tempo

# COMMAND ----------

from pyspark.sql.functions import expr, date_format

# Define o intervalo de datas desejado
data_inicial = "2023-01-01"
data_final = "2026-12-31"

# Calcula o número de dias no intervalo
num_dias = spark.sql(f"SELECT datediff('{data_final}', '{data_inicial}')").collect()[0][0]

# Cria um DataFrame com uma coluna contendo uma sequência de datas
df_calendario = spark.range(0, num_dias + 1) \
    .selectExpr(f"date_add(to_date('{data_inicial}'), CAST(id AS INT)) AS Data")

# Extrai os componentes de data
df_tempo = df_calendario.selectExpr(
    "Data",
    "year(Data) AS Ano",
    "month(Data) AS Mes",
       "(CASE month(Data) \
        WHEN 1 THEN 'JANEIRO' \
        WHEN 2 THEN 'FEVEREIRO' \
        WHEN 3 THEN 'MARCO' \
        WHEN 4 THEN 'ABRIL' \
        WHEN 5 THEN 'MAIO' \
        WHEN 6 THEN 'JUNHO' \
        WHEN 7 THEN 'JULHO' \
        WHEN 8 THEN 'AGOSTO' \
        WHEN 9 THEN 'SETEMBRO' \
        WHEN 10 THEN 'OUTUBRO' \
        WHEN 11 THEN 'NOVEMBRO' \
        WHEN 12 THEN 'DEZEMBRO' \
    END) AS NomeMes",
    "day(Data) AS Dia",
    "(CASE dayofweek(Data) \
        WHEN 1 THEN 'DOMINGO' \
        WHEN 2 THEN 'SEGUNDA-FEIRA' \
        WHEN 3 THEN 'TERCA-FEIRA' \
        WHEN 4 THEN 'QUARTA-FEIRA' \
        WHEN 5 THEN 'QUINTA-FEIRA' \
        WHEN 6 THEN 'SEXTA-FEIRA' \
        WHEN 7 THEN 'SABADO' \
    END) AS NomeDiaSemana",
    "dayofweek(Data) AS NumeroDiaSemana"
)

# Exibe o DataFrame resultante
df_tempo.display()

df_tempo.write.mode('overwrite').saveAsTable("gold.dim_tempo", format="delta")


# COMMAND ----------

# MAGIC %sql
# MAGIC drop table if exists gold.dim_clientes

# COMMAND ----------

# MAGIC %sql select * from clientes

# COMMAND ----------

# MAGIC %sql
# MAGIC create table gold.dim_clientes (
# MAGIC    SK_CLIENTE           bigint generated by default as identity,
# MAGIC    CODIGO_CLIENTE       int,
# MAGIC    NOME_CLIENTE         varchar(100),
# MAGIC    CIDADE               varchar(50),
# MAGIC    DATA_NASCIMENTO      date
# MAGIC )
# MAGIC USING DELTA;
# MAGIC

# COMMAND ----------

df_clientes.createOrReplaceTempView("clientes")

# COMMAND ----------

# MAGIC %sql
# MAGIC --v3a (COM CTE) prevendo atualizacao SCD1
# MAGIC WITH cliente_relacional AS (
# MAGIC 	SELECT codigo_cliente,
# MAGIC 		   nome,
# MAGIC 		   cidade,
# MAGIC 		   data_nascimento
# MAGIC 	  FROM clientes
# MAGIC )
# MAGIC MERGE INTO
# MAGIC 	gold.dim_clientes AS dc
# MAGIC USING
# MAGIC 	cliente_relacional AS cr
# MAGIC ON dc.codigo_cliente = cr.codigo_cliente   
# MAGIC
# MAGIC WHEN MATCHED AND (dc.codigo_cliente <> cr.codigo_cliente OR dc.cidade <> cr.cidade OR dc.nome_cliente <> cr.nome OR dc.data_nascimento <> cr.data_nascimento) THEN
# MAGIC
# MAGIC 	UPDATE SET codigo_cliente    = cr.codigo_cliente,
# MAGIC 	           nome_cliente          = cr.nome,
# MAGIC 			   cidade        = cr.cidade,
# MAGIC 			   data_nascimento = cr.data_nascimento
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC
# MAGIC 	INSERT (codigo_cliente, nome_cliente, cidade, data_nascimento)
# MAGIC 	VALUES (cr.codigo_cliente, cr.nome, cr.cidade, cr.data_nascimento)
# MAGIC
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from gold.dim_clientes

# COMMAND ----------

# MAGIC %sql
# MAGIC drop table if exists gold.dim_vendedores

# COMMAND ----------

# MAGIC %sql select * from vendedores;

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC create table gold.dim_vendedores (
# MAGIC    SK_VENDEDOR        bigint generated by default as identity,
# MAGIC    CODIGO_VENDEDOR     int,
# MAGIC    NOME_VENDEDOR       varchar(100),
# MAGIC    UNIDADE             varchar(50)
# MAGIC )
# MAGIC USING DELTA

# COMMAND ----------

# MAGIC %sql
# MAGIC --v3a (COM CTE) prevendo atualizacao SCD1
# MAGIC WITH vendedor_relacional AS (
# MAGIC 	SELECT codigo_vendedor,
# MAGIC 		   nome,
# MAGIC 		   unidade
# MAGIC 	  FROM vendedores m
# MAGIC )
# MAGIC MERGE INTO
# MAGIC 	gold.dim_vendedores AS d
# MAGIC USING
# MAGIC 	vendedor_relacional AS r
# MAGIC
# MAGIC ON r.codigo_vendedor = d.codigo_vendedor
# MAGIC
# MAGIC WHEN MATCHED AND (d.codigo_vendedor <> r.codigo_vendedor OR d.nome_vendedor <> r.nome OR d.unidade <> r.unidade) THEN
# MAGIC 	UPDATE SET codigo_vendedor = r.codigo_vendedor,
# MAGIC 		       nome_vendedor = r.nome,
# MAGIC 			   unidade    = r.unidade
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC 	INSERT (codigo_vendedor, nome_vendedor, unidade)
# MAGIC 	VALUES (r.codigo_vendedor, r.nome, r.unidade)
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from gold.dim_vendedores 

# COMMAND ----------

# MAGIC %sql drop table if exists gold.dim_produtos

# COMMAND ----------

# MAGIC %sql select * from ar_condicionados;

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC create table gold.dim_produtos (
# MAGIC    SK_PRODUTO        bigint generated by default as identity,
# MAGIC    CODIGO_PRODUTO      int,
# MAGIC    NOME_PRODUTO        varchar(100),
# MAGIC    NOME_MARCA          varchar(50),
# MAGIC    ANO                 int,
# MAGIC    FL_INVERTER         boolean,
# MAGIC    POTENCIA            varchar(50),
# MAGIC    VALOR               double
# MAGIC )
# MAGIC USING DELTA

# COMMAND ----------

# MAGIC %sql
# MAGIC WITH produto_relacional AS (
# MAGIC 	SELECT id,
# MAGIC 		   nome_modelo,
# MAGIC            nome_marca,
# MAGIC 		   ano,
# MAGIC            fl_inverter,
# MAGIC 		   potencia,
# MAGIC            valor
# MAGIC 	  FROM ar_condicionados
# MAGIC )
# MAGIC MERGE INTO
# MAGIC 	gold.dim_produtos AS d
# MAGIC USING
# MAGIC 	produto_relacional AS r
# MAGIC
# MAGIC ON r.id = d.codigo_produto
# MAGIC
# MAGIC WHEN MATCHED AND (d.codigo_produto <> r.id OR d.nome_produto <> r.nome_modelo OR d.nome_marca <> r.nome_marca OR d.ano <> r.ano OR d.fl_inverter <> r.fl_inverter OR d.potencia <> r.potencia OR d.valor <> r.valor) THEN
# MAGIC 	UPDATE SET codigo_produto = r.id,
# MAGIC 	           nome_produto = r.nome_modelo,
# MAGIC 	           nome_marca = r.nome_marca,
# MAGIC 	           ano = r.ano,
# MAGIC 	           fl_inverter = r.fl_inverter,
# MAGIC 	           potencia = r.potencia,
# MAGIC 	           valor = r.valor
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC 	INSERT (codigo_produto, nome_produto, nome_marca, ano, fl_inverter, potencia, valor)
# MAGIC 	VALUES (r.id, r.nome_modelo, r.nome_marca, r.ano, r.fl_inverter, r.potencia, r.valor)

# COMMAND ----------

# MAGIC %sql
# MAGIC drop table if exists gold.fato_vendas_ar_condicionados

# COMMAND ----------

# MAGIC %sql
# MAGIC create table gold.fato_vendas_ar_condicionados (
# MAGIC    FK_TEMPO             date,
# MAGIC    FK_CLIENTE           int,
# MAGIC    FK_VENDEDOR          int,
# MAGIC    FK_PRODUTO           int,
# MAGIC    ID_VENDA             int,
# MAGIC    QUANTIDADE           int,
# MAGIC    VALOR_UNITARIO       double,
# MAGIC    VALOR_TOTAL_VENDA    double
# MAGIC )
# MAGIC USING DELTA;

# COMMAND ----------

# MAGIC %sql
# MAGIC WITH source_fato_vendas AS (
# MAGIC     SELECT 
# MAGIC         v.DATA as FK_TEMPO,
# MAGIC         v.CODIGO_CLIENTE as FK_CLIENTE,
# MAGIC         v.CODIGO_VENDEDOR as FK_VENDEDOR,
# MAGIC         v.ID_PRODUTO as FK_PRODUTO,
# MAGIC         v.ID_VENDA,
# MAGIC         v.QUANTIDADE,
# MAGIC         ar.VALOR as VALOR_UNITARIO,
# MAGIC         (v.QUANTIDADE * ar.VALOR) as VALOR_TOTAL_VENDA
# MAGIC     FROM silver.vendas v
# MAGIC     LEFT JOIN silver.ar_condicionados ar
# MAGIC         ON v.ID_PRODUTO = ar.ID
# MAGIC )
# MAGIC
# MAGIC MERGE INTO gold.fato_vendas_ar_condicionados f
# MAGIC USING source_fato_vendas s
# MAGIC ON f.ID_VENDA = s.ID_VENDA
# MAGIC
# MAGIC WHEN MATCHED AND (
# MAGIC     f.FK_TEMPO <> s.FK_TEMPO OR 
# MAGIC     f.FK_CLIENTE <> s.FK_CLIENTE OR 
# MAGIC     f.FK_VENDEDOR <> s.FK_VENDEDOR OR 
# MAGIC     f.FK_PRODUTO <> s.FK_PRODUTO OR 
# MAGIC     f.QUANTIDADE <> s.QUANTIDADE OR 
# MAGIC     f.VALOR_TOTAL_VENDA <> s.VALOR_TOTAL_VENDA
# MAGIC ) THEN
# MAGIC     UPDATE SET 
# MAGIC         f.FK_TEMPO = s.FK_TEMPO,
# MAGIC         f.FK_CLIENTE = s.FK_CLIENTE,
# MAGIC         f.FK_VENDEDOR = s.FK_VENDEDOR,
# MAGIC         f.FK_PRODUTO = s.FK_PRODUTO,
# MAGIC         f.QUANTIDADE = s.QUANTIDADE,
# MAGIC         f.VALOR_UNITARIO = s.VALOR_UNITARIO,
# MAGIC         f.VALOR_TOTAL_VENDA = s.VALOR_TOTAL_VENDA
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC     INSERT (FK_TEMPO, FK_CLIENTE, FK_VENDEDOR, FK_PRODUTO, ID_VENDA, QUANTIDADE, VALOR_UNITARIO, VALOR_TOTAL_VENDA)
# MAGIC     VALUES (s.FK_TEMPO, s.FK_CLIENTE, s.FK_VENDEDOR, s.FK_PRODUTO, s.ID_VENDA, s.QUANTIDADE, s.VALOR_UNITARIO, s.VALOR_TOTAL_VENDA);

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from gold.fato_vendas_ar_condicionados
